stages:
  - test
  - deploy

rubocop-test:
  tags:
    - puppet
  script:
    - 'echo "inspecting following files with rubocop:"'
    - "rubocop25 -L"
    - "rubocop25 -l --only-guide-cops"
  stage: test

rake-test:
  tags:
    - puppet
  script:
    - "rake spec SPEC_OPTS='--format documentation'"
    - "rake metadata_lint"
    - "rake validate"
    - "rake lint"
    - "rake rubocop"
  stage: test

deploy:
  tags:
    - puppet
  script:
    - "/usr/local/bin/deploy.sh module apmd"
  stage: deploy
  only:
    - master

publish:
  tags:
    - puppet
  script:
    - rake module:clean
    - rake module:push
  stage: deploy
  only:
    - tags
